# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Stephanie Simms
tagline:          ''
description:      ''
url:              http://stephaniesimms.github.io

author:
  name:           'Stephanie Simms'
  url:            https://stephaniesimms.github.io

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
source: .
destination: ./_site
permalink: /:title
# paginate: 1
# paginate_path: /page:num/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stephaniesimms

plugins:
    - jekyll-sitemap
    - jekyll-paginate

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"